import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import ThemeWrapper from "@/src/Components/ThemeWrapper";
import Header from "@/src/Components/Header/Header";
import Footer from "@/src/Components/Footer/Footer";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Our Services - BzAnalytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.className} antialiased`}>
        <ThemeWrapper>
          <Header />

          {children}

          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
